'⚙ Setting':
  - '.github/**'
  - 'config/**'
  - 'scripts/**'

'✨ Feature':
  - 'src/features/**'
  - 'src/components/**'
  - 'src/pages/**'

'🌏 Deploy':
  - '.github/workflows/**'
  - 'Dockerfile'
  - 'docker-compose.yml'

'🎨 Html&css':
  - '**/*.html'
  - '**/*.css'
  - '**/*.scss'
  - '**/*.sass'

'📃 Docs':
  - '**/*.md'
  - 'docs/**'

'📬 API':
  - 'src/api/**'
  - 'src/services/**'

'🙋‍♂️ Question':
  - 'docs/questions/**'

'✅ Test':
  - '**/*.test.*'
  - 'src/**/*.stories.@(js|jsx|ts|tsx)'
  - '.storybook/**'
