name: '🚀 Feature Request'
description: '새로운 기능 요청'
labels: "feat"
title: '이슈 이름을 작성해주세요'
assignees: [author]
body:
  - type: input
    id: description
    attributes:
      label: '📄 이슈 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 구현기능(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: '📚 참조(References)'
      description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
      value: |
        - 참고자료
    validations:
      required: false