import type { Metadata } from 'next';
import './globals.css';
import { QueryProvider } from '@/components/providers/query-provider';
import { HouseMemoProvider } from '@/components/providers/house-memo-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-dvh overflow-hidden bg-gray-100 antialiased" suppressHydrationWarning>
        <HouseMemoProvider>
          <QueryProvider>{children}</QueryProvider>
        </HouseMemoProvider>
      </body>
    </html>
  );
}
